### ISSUE TITLE
Right clicking in a context menu outside of any of the frames doesn't open another context menu

### ISSUE THREAD

**Issue by CoderPuppy** [hbomb79/Titanium#27]
Caused by: https://github.com/hbomb79/Titanium/commit/d6bf2895f668cebfb18ce1654dac3bab6268b134

Also "closed" context menus (completely transparent, but still there) are blocking clicks

**Comment by hbomb79** [comment]
I have a feeling the best way to solve this is a custom handle function for `ContextMenus` so only clicks on sub-frames that are visible are marked used, rather than all mouse events as you linked.
